/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCodingIndexRouteImport } from './routes/student.coding.index'
import { Route as StudentCodingAssessmentSlugRouteImport } from './routes/student.coding.$assessmentSlug'
import { Route as StudentMcqIndexRouteImport } from './routes/student.mcq.index'
import { Route as StudentMcqTestSlugRouteImport } from './routes/student.mcq.$testSlug'
import { Route as StudentSeaAssessmentSlugRouteImport } from './routes/student.sea.$assessmentSlug'
import { Route as StudentSpokenEnglishAssessmentSlugRouteImport } from './routes/student.spoken-english.$assessmentSlug'
import { Route as StudentAssessmentMultisectionAssessmentSlugRouteImport } from './routes/student.assessment.multisection.$assessmentSlug'
import { Route as StudentPracticeSolveQuestionIdRouteImport } from './routes/student.practice.solve.$questionId'
import { Route as StudentPracticeCourseCourseIdQuestionIdRouteImport } from './routes/student.practice.course.$courseId.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCodingIndexRoute = StudentCodingIndexRouteImport.update({
  id: '/student/coding/',
  path: '/student/coding/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCodingAssessmentSlugRoute =
  StudentCodingAssessmentSlugRouteImport.update({
    id: '/student/coding/$assessmentSlug',
    path: '/student/coding/$assessmentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentMcqIndexRoute = StudentMcqIndexRouteImport.update({
  id: '/student/mcq/',
  path: '/student/mcq/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMcqTestSlugRoute = StudentMcqTestSlugRouteImport.update({
  id: '/student/mcq/$testSlug',
  path: '/student/mcq/$testSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSeaAssessmentSlugRoute =
  StudentSeaAssessmentSlugRouteImport.update({
    id: '/student/sea/$assessmentSlug',
    path: '/student/sea/$assessmentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentSpokenEnglishAssessmentSlugRoute =
  StudentSpokenEnglishAssessmentSlugRouteImport.update({
    id: '/student/spoken-english/$assessmentSlug',
    path: '/student/spoken-english/$assessmentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentAssessmentMultisectionAssessmentSlugRoute =
  StudentAssessmentMultisectionAssessmentSlugRouteImport.update({
    id: '/student/assessment/multisection/$assessmentSlug',
    path: '/student/assessment/multisection/$assessmentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentPracticeSolveQuestionIdRoute =
  StudentPracticeSolveQuestionIdRouteImport.update({
    id: '/student/practice/solve/$questionId',
    path: '/student/practice/solve/$questionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentPracticeCourseCourseIdQuestionIdRoute =
  StudentPracticeCourseCourseIdQuestionIdRouteImport.update({
    id: '/student/practice/course/$courseId/$questionId',
    path: '/student/practice/course/$courseId/$questionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/coding/$assessmentSlug': typeof StudentCodingAssessmentSlugRoute
  '/student/mcq/$testSlug': typeof StudentMcqTestSlugRoute
  '/student/sea/$assessmentSlug': typeof StudentSeaAssessmentSlugRoute
  '/student/spoken-english/$assessmentSlug': typeof StudentSpokenEnglishAssessmentSlugRoute
  '/student/coding/': typeof StudentCodingIndexRoute
  '/student/mcq/': typeof StudentMcqIndexRoute
  '/student/assessment/multisection/$assessmentSlug': typeof StudentAssessmentMultisectionAssessmentSlugRoute
  '/student/practice/solve/$questionId': typeof StudentPracticeSolveQuestionIdRoute
  '/student/practice/course/$courseId/$questionId': typeof StudentPracticeCourseCourseIdQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/coding/$assessmentSlug': typeof StudentCodingAssessmentSlugRoute
  '/student/mcq/$testSlug': typeof StudentMcqTestSlugRoute
  '/student/sea/$assessmentSlug': typeof StudentSeaAssessmentSlugRoute
  '/student/spoken-english/$assessmentSlug': typeof StudentSpokenEnglishAssessmentSlugRoute
  '/student/coding': typeof StudentCodingIndexRoute
  '/student/mcq': typeof StudentMcqIndexRoute
  '/student/assessment/multisection/$assessmentSlug': typeof StudentAssessmentMultisectionAssessmentSlugRoute
  '/student/practice/solve/$questionId': typeof StudentPracticeSolveQuestionIdRoute
  '/student/practice/course/$courseId/$questionId': typeof StudentPracticeCourseCourseIdQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/coding/$assessmentSlug': typeof StudentCodingAssessmentSlugRoute
  '/student/mcq/$testSlug': typeof StudentMcqTestSlugRoute
  '/student/sea/$assessmentSlug': typeof StudentSeaAssessmentSlugRoute
  '/student/spoken-english/$assessmentSlug': typeof StudentSpokenEnglishAssessmentSlugRoute
  '/student/coding/': typeof StudentCodingIndexRoute
  '/student/mcq/': typeof StudentMcqIndexRoute
  '/student/assessment/multisection/$assessmentSlug': typeof StudentAssessmentMultisectionAssessmentSlugRoute
  '/student/practice/solve/$questionId': typeof StudentPracticeSolveQuestionIdRoute
  '/student/practice/course/$courseId/$questionId': typeof StudentPracticeCourseCourseIdQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/guest'
    | '/home'
    | '/login'
    | '/student/dashboard'
    | '/student/coding/$assessmentSlug'
    | '/student/mcq/$testSlug'
    | '/student/sea/$assessmentSlug'
    | '/student/spoken-english/$assessmentSlug'
    | '/student/coding/'
    | '/student/mcq/'
    | '/student/assessment/multisection/$assessmentSlug'
    | '/student/practice/solve/$questionId'
    | '/student/practice/course/$courseId/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/guest'
    | '/home'
    | '/login'
    | '/student/dashboard'
    | '/student/coding/$assessmentSlug'
    | '/student/mcq/$testSlug'
    | '/student/sea/$assessmentSlug'
    | '/student/spoken-english/$assessmentSlug'
    | '/student/coding'
    | '/student/mcq'
    | '/student/assessment/multisection/$assessmentSlug'
    | '/student/practice/solve/$questionId'
    | '/student/practice/course/$courseId/$questionId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/guest'
    | '/home'
    | '/login'
    | '/student/dashboard'
    | '/student/coding/$assessmentSlug'
    | '/student/mcq/$testSlug'
    | '/student/sea/$assessmentSlug'
    | '/student/spoken-english/$assessmentSlug'
    | '/student/coding/'
    | '/student/mcq/'
    | '/student/assessment/multisection/$assessmentSlug'
    | '/student/practice/solve/$questionId'
    | '/student/practice/course/$courseId/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GuestRoute: typeof GuestRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentCodingAssessmentSlugRoute: typeof StudentCodingAssessmentSlugRoute
  StudentMcqTestSlugRoute: typeof StudentMcqTestSlugRoute
  StudentSeaAssessmentSlugRoute: typeof StudentSeaAssessmentSlugRoute
  StudentSpokenEnglishAssessmentSlugRoute: typeof StudentSpokenEnglishAssessmentSlugRoute
  StudentCodingIndexRoute: typeof StudentCodingIndexRoute
  StudentMcqIndexRoute: typeof StudentMcqIndexRoute
  StudentAssessmentMultisectionAssessmentSlugRoute: typeof StudentAssessmentMultisectionAssessmentSlugRoute
  StudentPracticeSolveQuestionIdRoute: typeof StudentPracticeSolveQuestionIdRoute
  StudentPracticeCourseCourseIdQuestionIdRoute: typeof StudentPracticeCourseCourseIdQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/coding/': {
      id: '/student/coding/'
      path: '/student/coding'
      fullPath: '/student/coding/'
      preLoaderRoute: typeof StudentCodingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/coding/$assessmentSlug': {
      id: '/student/coding/$assessmentSlug'
      path: '/student/coding/$assessmentSlug'
      fullPath: '/student/coding/$assessmentSlug'
      preLoaderRoute: typeof StudentCodingAssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/mcq/': {
      id: '/student/mcq/'
      path: '/student/mcq'
      fullPath: '/student/mcq/'
      preLoaderRoute: typeof StudentMcqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/mcq/$testSlug': {
      id: '/student/mcq/$testSlug'
      path: '/student/mcq/$testSlug'
      fullPath: '/student/mcq/$testSlug'
      preLoaderRoute: typeof StudentMcqTestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/sea/$assessmentSlug': {
      id: '/student/sea/$assessmentSlug'
      path: '/student/sea/$assessmentSlug'
      fullPath: '/student/sea/$assessmentSlug'
      preLoaderRoute: typeof StudentSeaAssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/spoken-english/$assessmentSlug': {
      id: '/student/spoken-english/$assessmentSlug'
      path: '/student/spoken-english/$assessmentSlug'
      fullPath: '/student/spoken-english/$assessmentSlug'
      preLoaderRoute: typeof StudentSpokenEnglishAssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessment/multisection/$assessmentSlug': {
      id: '/student/assessment/multisection/$assessmentSlug'
      path: '/student/assessment/multisection/$assessmentSlug'
      fullPath: '/student/assessment/multisection/$assessmentSlug'
      preLoaderRoute: typeof StudentAssessmentMultisectionAssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice/solve/$questionId': {
      id: '/student/practice/solve/$questionId'
      path: '/student/practice/solve/$questionId'
      fullPath: '/student/practice/solve/$questionId'
      preLoaderRoute: typeof StudentPracticeSolveQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice/course/$courseId/$questionId': {
      id: '/student/practice/course/$courseId/$questionId'
      path: '/student/practice/course/$courseId/$questionId'
      fullPath: '/student/practice/course/$courseId/$questionId'
      preLoaderRoute: typeof StudentPracticeCourseCourseIdQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GuestRoute: GuestRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentCodingAssessmentSlugRoute: StudentCodingAssessmentSlugRoute,
  StudentMcqTestSlugRoute: StudentMcqTestSlugRoute,
  StudentSeaAssessmentSlugRoute: StudentSeaAssessmentSlugRoute,
  StudentSpokenEnglishAssessmentSlugRoute:
    StudentSpokenEnglishAssessmentSlugRoute,
  StudentCodingIndexRoute: StudentCodingIndexRoute,
  StudentMcqIndexRoute: StudentMcqIndexRoute,
  StudentAssessmentMultisectionAssessmentSlugRoute:
    StudentAssessmentMultisectionAssessmentSlugRoute,
  StudentPracticeSolveQuestionIdRoute: StudentPracticeSolveQuestionIdRoute,
  StudentPracticeCourseCourseIdQuestionIdRoute:
    StudentPracticeCourseCourseIdQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
